### PR TITLE
Add bedtools intersect

### PR DESCRIPTION
**Pull request by marrip**
### This PR:

Added: bedtools_intersect rule and required files
Changed: computational generation of output files, adapt newer resource definitions

### CODE REVIEW

**Comment by jonca79** [comment]
Isn't there now a problem with rules doing the same thing?

**Comment by marrip** [comment]
Could you be a bit more specific?

**Comment by jonca79** [comment]
That we have samtools_index both in misc and under alignment and bgzip in misc and under filtering

**Comment by marrip** [comment]
True. I think they fit better in `misc` tbh. But do you think that it is a problem to have them twice? 🤔

**Comment by Smeds** [comment]
Having it multiple times may require ruleorder to be set. If we include it multiple times we should maybee write something about it in the readme.

**Review by jonca79 — APPROVED** [review]

**Pull request merged**
